api_version = "2024-10"

[[extensions]]
name = "Afforestation Flow"
handle = "afforestation-flow"
uid = "7d29a290-137b-9a7f-18a5-b4fa3c1a7bed005e7ce9"
type = "flow_action"
runtime_url = "https://afforestation-shopify-app-production.up.railway.app/flow/plant-trees"

  [extensions.settings]
  
  [[extensions.settings.fields]]
  key = "tree_count"
  name = "Number of Trees"
  description = "How many trees to plant"
  type = "number_integer"
  required = true
  
  [[extensions.settings.fields]]
  key = "reason"
  name = "Reason"
  description = "Why trees are being planted (for tracking)"
  type = "single_line_text_field"
  required = false

[[extensions]]
name = "Afforestation CO2 Offset"
handle = "afforestation-carbon"
uid = "2b826751-1104-6600-c0cc-f845a0351b9b51935dd9"
type = "flow_action"
runtime_url = "https://afforestation-shopify-app-production.up.railway.app/flow/offset-carbon"

  [extensions.settings]
  
  [[extensions.settings.fields]]
  key = "kg_co2"
  name = "kg of CO2 to Offset"
  description = "Amount of carbon dioxide to offset in kilograms"
  type = "number_decimal"
  required = true
  
  [[extensions.settings.fields]]
  key = "reason"
  name = "Reason"
  description = "Why carbon is being offset (for tracking)"
  type = "single_line_text_field"
  required = false
